# This GitHub workflow deploys Bundle resources (ML resource config and more)
# defined under my_mlops_project/resources/*
# and my_mlops_project/bundle.yml with staging environment configs,
# when PRs are merged into the default branch
name: Bundle Deployment for my-mlops-project Staging

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

defaults:
  run:
    working-directory: ./my_mlops_project

env:
  DATABRICKS_TOKEN: ${{ secrets.STAGING_WORKSPACE_TOKEN }}

jobs:
  staging:
    concurrency: my-mlops-project-staging-bundle-job
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: databricks/setup-cli@main
      - name: Validate Bundle For Staging Environment
        id: validate
        run: |
          databricks bundle validate -e staging
      - name: Deploy Bundle to Staging Environment
        id: deploy
        run: |
          databricks bundle deploy -e staging
